try {
    anotherFn();
} catch (e) {
    console.log('error in anotherFn');
}

try {
    hello();
} catch (e) {
    console.log(e);
}